apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: goapp241210a 
  janus-idp.io/tekton: goapp241210a
  backstage.io/kubernetes-id: goapp241210a
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: goapp241210a
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  